var imgKilde = [
                {navn: "Sirkel", kilde: "./sirkel.png", info: "En sirkel deler planet i to områder, akkurat som alle mangekanter gjør det: en indre sirkelflate og et ytre område. Noen ganger mener vi sirkelflaten når vi sier sirkel. For eksempel er det helt vanlig å snakke om arealet til en sirkel. Selve kurven som danner sirkelen, kalles da periferien."},
                {navn: "Femkant", kilde: "./femkant.png", info: "I geometri er en femkant en figur med fem sider og fem vinkler. En femkant er dermed en polygon med fem hjørner. En femkant kalles også en pentagon."},
                {navn: "Kvadrat", kilde: "./kvadrat.png", info: "Et kvadrat er en sammenhengende geometrisk figur som består av fire like lange linjestykker som er parvis parallelle og der vinkelen mellom linjestykker som ikke er parallelle er 90°. De kan defineres enten som en regulær firkant eller et rektangel med to like lange tilstøtende kanter."},
                {navn: "Likebeint trekat", kilde: "./likebeintTrekant.png", info: "En trekant er et polygon med tre sidekanter og tre hjørner, en geometrisk figur sammensatt av tre linjestykker. I euklidsk geometri er dette den enkleste form for polygon. I matematikk kan en trekant også omtales som en trigon. Ordet triangel kan også brukes for å omtale en trekant. En trekant med hjørner A, B og C. I en likebeint trekant er to av sidene like lange. Den tredje siden kalles gjerne grunnlinjen. De to vinklene mellom de like lange sidene og grunnlinjen vil være like store."},
                {navn: "Parallellogram", kilde: "./parallellogram.png", info: "Et parallellogram er i geometri en firkant med følgende egenskaper: Sidekantene er parvis parallelle. Sidekantene er parvis like lange. Motstående vinkler er parvis like store. Diagonalene i et parallellogram deler hverandre på midten."},
                {navn: "Stjerne", kilde: "./stjerne.png", info: "Pentagrammet og lignende stjerneformer forekommer i flere kulturkretser og går langt tilbake i tid. Pentagrammet er litt forskjellig fra heksagrammet som har seks takker, men de to figurene har til dels vært brukt noe om hverandre, og forekommer som varianter blant annet i bumerker."},
                {navn: "Trapes", kilde: "./trapes.png", info: "Et trapes er en firkant med (minst) to parallelle sider. Høyden i et trapes er den vinkelrette avstanden mellom de to parallelle sidene."}
];
//Lett å legge til nye figurer bare gi et navn og kilde til bilde + litt info fra Wikipedia så kommer den opp på alle sidene